[build]
  publish = "."

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/problem"
  to = "/problem.html"
  status = 200

[[redirects]]
  from = "/solution"
  to = "/solution.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/resources.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
